### ISSUE TITLE
PluginNotFound: plugin pybtex.style.names.plain not found

### ISSUE THREAD

**Issue by Playerrrrr** [blackadad/paper-scraper#2]
Running into an issue, no matter what version of pybtex I tried to install. 
(So far manually tried with 0.20.0; 0.22.2; 0.24.0)

Code:

import paperscraper

keyword_search = 'meta-reinforcement learning meta reinforcement learning'
papers = paperscraper.search_papers(keyword_search)
docs = paperqa.Docs()
for path,data in papers.items():
    try:
        docs.add(path, data['citation'], data['key'])
    except ValueError as e:
        print('Could not read', path, e)
answer = docs.query("What are the applications of a meta reinforcement learning and its contributions?")
print(answer.formatted_answer)

Error: 

---------------------------------------------------------------------------
PluginNotFound                            Traceback (most recent call last)
[<ipython-input-7-b116bc80d401>](https://localhost:8080/#) in <module>
      2 
      3 keyword_search = 'meta-reinforcement learning meta reinforcement learning'
----> 4 papers = paperscraper.search_papers(keyword_search)
      5 docs = paperqa.Docs()
      6 for path,data in papers.items():

4 frames
[/usr/local/lib/python3.8/dist-packages/pybtex/plugin/__init__.py](https://localhost:8080/#) in _load_entry_point(group, name, use_aliases)
     79         for entry_point in pkg_resources.iter_entry_points(search_group, name):
     80             return entry_point.load()
---> 81     raise PluginNotFound(group, name)
     82 
     83 

PluginNotFound: plugin pybtex.style.names.plain not found

**Comment by blackadad** [comment]
This should have been fixed in latest version. Can you confirm your paper-scraper version?

**Comment by Playerrrrr** [comment]
print(paperscraper.__version__)
0.0.3

**Comment by blackadad** [comment]
I'm really having trouble reproducing this - can you share your code?

**Comment by Playerrrrr** [comment]
pip install paper-qa
pip install git+https://github.com/blackadad/paper-scraper.git

import os
os.environ['OPENAI_API_KEY'] =

import paperqa
from paperqa import Docs
import paperscraper

keyword_search = 'meta-reinforcement learning meta reinforcement learning'
papers = paperscraper.search_papers(keyword_search)
docs = paperqa.Docs()
for path,data in papers.items():
    try:
        docs.add(path, data['citation'], data['key'])
    except ValueError as e:
        # sometimes this happens if PDFs aren't downloaded or readable
        print('Could not read', path, e)
# takes ~ 1 min and costs $0.50 to execute this line
answer = docs.query("What are the applications of a meta reinforcement learning and its contributions?")
print(answer.formatted_answer)

---------------------------------------------------------------------------
PluginNotFound                            Traceback (most recent call last)
Cell In [4], line 6
      3 import paperscraper
      5 keyword_search = 'meta-reinforcement learning meta reinforcement learning'
----> 6 papers = paperscraper.search_papers(keyword_search)
      7 docs = paperqa.Docs()
      8 for path,data in papers.items():

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\paperscraper\lib.py:219, in search_papers(query, limit, pdir, verbose, _paths, _limit, _offset)
    216 bibtex = paper["citationStyles"]["bibtex"]
    217 key = bibtex.split("{")[1].split(",")[0]
    218 paths[path] = dict(
--> 219     citation=format_bibtex(bibtex, key), key=key, bibtex=bibtex
    220 )
    221 if verbose:
    222     print("Succeeded - key:", key)

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\paperscraper\lib.py:63, in format_bibtex(bibtex, key)
     60 from pybtex.database import parse_string
     61 from pybtex.style.formatting import unsrtalpha
---> 63 style = unsrtalpha.Style()
     64 try:
     65     bd = parse_string(clean_upbibtex(bibtex), "bibtex")
...
     79     for entry_point in pkg_resources.iter_entry_points(search_group, name):
     80         return entry_point.load()
---> 81 raise PluginNotFound(group, name)

PluginNotFound: plugin pybtex.style.names.plain not found

**Comment by Playerrrrr** [comment]
Should we try cross-checking the version of the other dependencies/libraries?

**Comment by blackadad** [comment]
Not sure why, but if I restart the colab after installing packages it fixes the bug. I think there is some version of `pybtex` install by default in colab and it has to be replaced via a restart.

**Comment by Playerrrrr** [comment]
I have noticed that the log of the "pip install git+https://github.com/blackadad/paper-scraper.git" was installing the version 0.1.0, hence tried to manually install the correct "0.0.3" and got an error that it does not exist? And when I checked the current version it says that the version is indeed 0.1.0 . Any thoughts? 
![image](https://user-images.githubusercontent.com/77760472/221420714-6a90347b-38ee-456e-ab0a-8298c7e36d24.png)

**Comment by Playerrrrr** [comment]
Started a new instance and tried re-running everything and ran into a new error type? 
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-18-b116bc80d401>](https://localhost:8080/#) in <module>
      2 
      3 keyword_search = 'meta-reinforcement learning meta reinforcement learning'
----> 4 papers = paperscraper.search_papers(keyword_search)
      5 docs = paperqa.Docs()
      6 for path,data in papers.items():

2 frames
[/usr/lib/python3.8/asyncio/base_events.py](https://localhost:8080/#) in _check_running(self)
    550     def _check_running(self):
    551         if self.is_running():
--> 552             raise RuntimeError('This event loop is already running')
    553         if events._get_running_loop() is not None:
    554             raise RuntimeError(

RuntimeError: This event loop is already running

**Comment by blackadad** [comment]
In colab, you need this code:

```py
import nest_asyncio
nest_asyncio.apply()
```
