### ISSUE TITLE
DOI2PDF - What am I setting for the env var? 

### ISSUE THREAD

**Issue by caretak3r** [blackadad/paper-scraper#7]
Keep seeing these errors:

2023-07-12 09:01:08,398 - paper-scraper - INFO - 	Scraper doi failed: No DOI2PDF environment variable set (scraper.py:69)

Am I supposed to set the base_url for DOI documents I want?

**Comment by caretak3r** [comment]
^bump

**Comment by igor-krawczuk** [comment]
@caretak3r This is meant playful and based on my intution of the repo authors intention. [See this link](https://letmegooglethat.com/?q=which+website+gives+you+almost+any+scientific+paper+pdf+you+can+provide+a+DOI+for)

Just be careful, sometimes that link gives an answer that is in the cited legal gray zone
